name: Code Review GPT

on:
  pull_request:
    branches: [main]

jobs:
  run_code_review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Code Review GPT
        uses: mattzcarey/code-review-gpt@v0.1.11
        with:
          GITHUB_TOKEN: ${{ github.token }}
          OPENAI_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }} 
          MODEL: "deepseek-chat-32k"  
          REVIEW_LANGUAGE: "English"
        env:
          OPENAI_BASE_URL: "https://api.deepseek.com/v1"  
