name: Code Review GPT

      

on:
  pull_request:
    branches: [master]

jobs:
  run_code_review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Debug - Check if Key Exists
        run: |
          if [ -n "${{ secrets.DEEPSEEK_API_KEY }}" ]; then
            echo "✅ 密钥已成功读取"
          else
            echo "❌ 未检测到密钥，请检查 Secrets 配置"
          fi

      - name: Debug - Check if github key Exists
        run: |
          if [ -n "${{ github.token }}" ]; then
            echo "✅ git密钥已成功读取"
          else
            echo "❌ git未检测到密钥，请检查 Secrets 配置"
          fi
          
      - name: Code Review GPT
        uses: mattzcarey/code-review-gpt@v0.8.0
        with:
          GITHUB_TOKEN: ${{ github.token }}
          OPENAI_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }} 
          MODEL: "deepseek-chat"  
          REVIEW_LANGUAGE: "English"
        env:
          OPENAI_BASE_URL: "https://api.deepseek.com/v1"  
